// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNF8BDCC10Q6uCYFAp6B4LyaSKrG8UZ_U',
    appId: '1:351706241322:web:1b4ff9acdbf3e500b02653',
    messagingSenderId: '351706241322',
    projectId: 'design-patterns-665ae',
    authDomain: 'design-patterns-665ae.firebaseapp.com',
    storageBucket: 'design-patterns-665ae.firebasestorage.app',
    measurementId: 'G-1GS4257788',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuB-u1NCF57lkKQHz6xvke5Wfbq6JWOzU',
    appId: '1:351706241322:android:0337c451fa6b1b0db02653',
    messagingSenderId: '351706241322',
    projectId: 'design-patterns-665ae',
    storageBucket: 'design-patterns-665ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtaQknemRicuqMcKJEeC-pDaCx4dWXt8g',
    appId: '1:351706241322:ios:00d430872e474c4fb02653',
    messagingSenderId: '351706241322',
    projectId: 'design-patterns-665ae',
    storageBucket: 'design-patterns-665ae.firebasestorage.app',
    iosBundleId: 'com.cyberfanta.designPatterns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtaQknemRicuqMcKJEeC-pDaCx4dWXt8g',
    appId: '1:351706241322:ios:00d430872e474c4fb02653',
    messagingSenderId: '351706241322',
    projectId: 'design-patterns-665ae',
    storageBucket: 'design-patterns-665ae.firebasestorage.app',
    iosBundleId: 'com.cyberfanta.designPatterns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNF8BDCC10Q6uCYFAp6B4LyaSKrG8UZ_U',
    appId: '1:351706241322:web:3260a107fc76620cb02653',
    messagingSenderId: '351706241322',
    projectId: 'design-patterns-665ae',
    authDomain: 'design-patterns-665ae.firebaseapp.com',
    storageBucket: 'design-patterns-665ae.firebasestorage.app',
    measurementId: 'G-VBXLN761LS',
  );
}
